- id: '1663625931053'
  alias: 'Tasmota Discovery: ProfiCook PC-WKS 1167 G Kettle'
  description: ''
  use_blueprint:
    path: tasmota/discovery_proficook-kettle.yaml
    input:
      tasmota_device: b48211371680355362913c510caf24cf
      topic: tasmota_D06ADD
- id: '1670100879589'
  alias: Turn on Christmas lights
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: cb4267657cb9ed3e341118c8152802df
    entity_id: switch.tasmota_4
    domain: switch
  mode: single
- id: '1670100954998'
  alias: Turn off Christmas lights
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: cb4267657cb9ed3e341118c8152802df
    entity_id: switch.tasmota_4
    domain: switch
  mode: single
